### ISSUE TITLE
include comments in lexer

### ISSUE THREAD

**Issue by flixm16** [Servostar/gemstone#33]
include comments in lexer with the form:
```
# <every possible symbol> \n
```

don't forget to increment the linenumber after a comment

**Comment by Servostar** [comment]
Make sure to increment `yylineno`.

**Comment by Servostar** [comment]
Consider returning `\n` in lexer

**Comment by flixm16** [comment]
consider using `#.*` for comments, because `#` starts a comment and `.*` matches any character except line terminators. with this the linebreak is seperated from the comment and yylineno can use it
